/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterFace;

import DAO.BacLuongDAO;
import DAO.LuongCoBanDAO;
import DAO.PhuCapDAO;
import DAO.QuanLyLuongDAO;
import Helper.MsgBox;
import Model.BacLuong;
import Model.Luong;
import Model.LuongCoBan;
import Model.PhuCap;
import java.awt.Color;
import java.text.ParseException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLyLuongJInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyLuongJInternal
     */
    public QuanLyLuongJInternal() {
        initComponents();
        init();
    }

    void init() {
        this.fillComboBoxBacLuong();
        this.fillComboBoxLuongCoBan();
        this.fillComboBoxPhuCap();
        this.fillToTable();
    }

    QuanLyLuongDAO dao = new QuanLyLuongDAO();
    PhuCapDAO pcdao = new PhuCapDAO();
    BacLuongDAO bldao = new BacLuongDAO();
    LuongCoBanDAO lcbdao = new LuongCoBanDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoNgayLam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGioLamThem = new javax.swing.JTextField();
        btnSeach = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboBacLuong = new javax.swing.JComboBox<>();
        cboLuongCoBan = new javax.swing.JComboBox<>();
        txtTamUng = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        cboThang = new javax.swing.JComboBox<>();
        txtTienThuong = new javax.swing.JTextField();
        cboPhuCap = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtThucLinh = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("QUẢN LÝ LƯƠNG");

        jLabel1.setText("Tháng lương:");

        cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029" }));

        jLabel2.setText("Mã nhân viên:");

        jLabel3.setText("Tên nhân viên:");

        jLabel4.setText("Số ngày làm:");

        jLabel5.setText("Giờ làm thêm:");

        txtGioLamThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioLamThemActionPerformed(evt);
            }
        });

        btnSeach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btnSeach.setText("Tìm kiếm");
        btnSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachActionPerformed(evt);
            }
        });

        jLabel6.setText("Tiền thưởng:");

        jLabel7.setText("Phụ cấp:");

        jLabel8.setText("Tạm ứng:");

        jLabel9.setText("Bậc lương:");

        jLabel10.setText("Lương cơ bản:");

        cboBacLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBacLuongActionPerformed(evt);
            }
        });

        cboLuongCoBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLuongCoBanActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Document.png"))); // NOI18N
        btnThoat.setText("Mới");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tblLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Năm", "Tháng", "Mã NV", "Tên NV", "Số ngày làm", "Giờ làm thêm", "Phụ cấp", "Bậc lương", "Lương cơ bản", "Tạm ứng", "Tiền thưởng", "Thực lĩnh"
            }
        ));
        tblLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLuongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLuong);

        jLabel11.setText("Năm:");

        cboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cboPhuCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aa" }));
        cboPhuCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPhuCapActionPerformed(evt);
            }
        });

        jLabel12.setText("Thực lĩnh:");

        txtThucLinh.setText("0.0");
        txtThucLinh.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtThucLinhCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnSeach))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboBacLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboLuongCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtThucLinh, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addComponent(txtTienThuong)
                                .addComponent(txtTamUng)
                                .addComponent(cboPhuCap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboBacLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(cboLuongCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeach)
                    .addComponent(jLabel7)
                    .addComponent(cboPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTamUng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTienThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGioLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtThucLinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnSua))
                    .addComponent(btnXoa)
                    .addComponent(btnThoat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblLuong.getModel();
        model.setRowCount(0);//clear table
        try {
            for (Luong tk : dao.getAllLuong()) {
                Object rowData[] = new Object[12];
                rowData[0] = tk.getNam();
                rowData[1] = tk.getThang();
                rowData[2] = tk.getMaNV();
                rowData[3] = tk.getTenNV();
                rowData[4] = tk.getSoNgayLam();
                rowData[5] = tk.getGioLamThem();
                rowData[6] = tk.getPhuCap();
                rowData[7] = tk.getBacLuong();
                rowData[8] = tk.getLuongCoBan();
                rowData[9] = tk.getTamUng();
                rowData[10] = tk.getTienThuong();
                rowData[11] = tk.getThucLinh();
                model.addRow(rowData);
            }
        } catch (Exception e) {
               e.printStackTrace();
        }
    }

    void fillComboBoxPhuCap() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboPhuCap.getModel(); //kết nối model với cbo
        model.removeAllElements();   //xóa toàn bộ item của cbo
        try {
            List<PhuCap> list = pcdao.getAllPhuCap();
            for (PhuCap cd : list) {
                model.addElement(cd);    //thêm đối tượng (Object) vào model
                //chỉ thêm đc đối tượng đối với model, cbo chỉ được cbo.addItem(String);
                //lấy đối tượng thì từ cbo cũng được: cbo.getSelectedItem();
            }
            cboPhuCap.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void chonPhuCap() {
        PhuCap pc = (PhuCap) cboPhuCap.getSelectedItem();
//        model.setMaCD(ChuyenDe.getMaCD());
    }

    void fillComboBoxBacLuong() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboBacLuong.getModel(); //kết nối model với cbo
        model.removeAllElements();   //xóa toàn bộ item của cbo
        try {
            List<BacLuong> list = bldao.getAllBacLuong();
            for (BacLuong cd : list) {
                model.addElement(cd);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void chonLuongCoBan() {
        LuongCoBan lcb = (LuongCoBan) cboLuongCoBan.getSelectedItem();
    }

    void fillComboBoxLuongCoBan() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLuongCoBan.getModel(); //kết nối model với cbo
        model.removeAllElements();   //xóa toàn bộ item của cbo
        try {
            List<LuongCoBan> list = lcbdao.getAllLuongCoBan();
            for (LuongCoBan cd : list) {
                model.addElement(cd);
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void chonBacLuong() {
        BacLuong bl = (BacLuong) cboBacLuong.getSelectedItem();
    }

    public boolean ValidateForm() {
        if (txtMaNV.getText().isEmpty() || txtTenNV.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin");
            return false;
        }
        return true;
    }

    public Luong getModel() throws ParseException {
        Luong tk = new Luong();
        tk.setNam(cboNam.getSelectedItem().toString());
        tk.setThang(cboThang.getSelectedItem().toString());
        tk.setMaNV(txtMaNV.getText());
        tk.setTenNV(txtTenNV.getText());
        tk.setSoNgayLam(txtSoNgayLam.getText());
        tk.setGioLamThem(txtGioLamThem.getText());
        PhuCap PhuCap = (PhuCap) cboPhuCap.getSelectedItem();
        tk.setPhuCap(PhuCap.getMaPhuCap());
        BacLuong BacLuong = (BacLuong) cboBacLuong.getSelectedItem();
        tk.setBacLuong(BacLuong.getMaBacLuong());
        LuongCoBan LuongCoBan = (LuongCoBan) cboLuongCoBan.getSelectedItem();
        tk.setPhuCap(LuongCoBan.getMaLuongCoBan());
//        tk.setBacLuong(cboBacLuong);
//        tk.setLuongCoBan(cboLuongCoBan);
        tk.setTamUng(txtTamUng.getText());
        tk.setTienThuong(txtTienThuong.getText());
        tk.setThucLinh(txtThucLinh.getText());

        return tk;
    }

    public void setModel(BacLuong tk) {
//        txtMaBacLuong.setText(tk.getMaBacLuong());
//        txtBacLuong.setText((String.valueOf(tk.getBacLuong())));
    }

    private void btnSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachActionPerformed
//                if (txtMa.getText().equals("")) {
//                    JOptionPane.showMessageDialog(this, "Chưa nhập mã nhân viên");
//                    return;
//                }
//                try {
//                    NhanVienDAO dao = new NhanVienDAO();
//                    NhanVien ns = dao.findById(txtMa.getText());
//        
//                    if (ns != null) {
//                        txtMa.setText(ns.getMaNV());
//                        txtTen.setText(ns.getTenNV());
//        
//                        txtTrinhDo.setText(ns.getTrinhDo());
//                        txtDiaChi.setText(ns.getDiaChi());
//                        txtNgaySinh.setText(ns.getNgaySinh());
//                        txtChucVu.setText(ns.getChucVu());
//                        txtMaPhong.setText(ns.getMaPhong());
//                        rdoNam.setSelected(ns.getGioiTinh() == 1);
//                        rdoNu.setSelected(ns.getGioiTinh() == 0);
//                        txtBacLuong.setText(ns.getBacLuong());
//                        txtMaThuong.setText(ns.getMaThuong());
//                        txtMaPhuCap.setText(ns.getMaPC());
//                    } else {
//                        JOptionPane.showMessageDialog(this, "Mã nhân viên không đúng");
//                    }
//                } catch (Exception e) {
//                    //JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
//                    //e.printStackTrace();
//                }
    }//GEN-LAST:event_btnSeachActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
                StringBuilder sb = new StringBuilder();
                if (txtMaNV.getText().equals("")) {
                    sb.append("Mã nhân viên không được để trống!\n");
                    txtMaNV.setBackground(Color.red);
                } else {
                    txtMaNV.setBackground(Color.white);
                }
                if (txtTenNV.getText().equals("")) {
                    sb.append("Tên NV không được để trống!\n");
                    txtTenNV.setBackground(Color.red);
                } else {
                    txtTenNV.setBackground(Color.white);
                }
                if (sb.length() > 0) {
                    JOptionPane.showMessageDialog(this, sb);
                    return;
                }
                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm lương mới không?") == JOptionPane.NO_OPTION) {
                    return;
                }
        
                try {
                    Luong ns = new Luong();
                    ns.setNam(cboNam.getToolTipText());
                    ns.setThang(cboThang.getToolTipText());
                    ns.setMaNV(txtMaNV.getText());
                    ns.setTenNV(txtTenNV.getText());
                    ns.setSoNgayLam(txtSoNgayLam.getText());
                    ns.setGioLamThem(txtGioLamThem.getText());
                    ns.setPhuCap(cboPhuCap.getToolTipText());
                    ns.setBacLuong(cboBacLuong.getToolTipText());
                    ns.setLuongCoBan(cboLuongCoBan.getToolTipText());
                    ns.setTamUng(txtTamUng.getText());
                    ns.setTienThuong(txtTienThuong.getText());
                    ns.setThucLinh(txtThucLinh.getText());
        
                    QuanLyLuongDAO dao = new QuanLyLuongDAO();
                    dao.add(ns);
                    MsgBox.alert(this, "Thêm thành công vào CSDL!");
                    fillToTable();
                    //reset();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại, mã nhân viên đã tồn tại trong CSDL");
                    e.printStackTrace();
                }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        //        StringBuilder sb = new StringBuilder();
        //        if (txtMa.getText().equals("")) {
        //            sb.append("Mã nhân viên viên không được để trống!");
        //            txtMa.setBackground(Color.red);
        //        } else {
        //            txtMa.setBackground(Color.white);
        //        }
        //        if (sb.length() > 0) {
        //            JOptionPane.showMessageDialog(this, sb);
        //            return;
        //        }
        //        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật nhân viên không?") == JOptionPane.NO_OPTION) {
        //            return;
        //        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        //        StringBuilder sb = new StringBuilder();
        //        if (txtMa.getText().equals("")) {
        //            sb.append("Mã nhân viên không được để trống!");
        //            txtMa.setBackground(Color.red);
        //        } else {
        //            txtMa.setBackground(Color.white);
        //        }
        //        if (sb.length() > 0) {
        //            JOptionPane.showMessageDialog(this, sb);
        //            return;
        //        }
        //        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa nhân viên không?") == JOptionPane.NO_OPTION) {
        //            return;
        //        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLuongMouseClicked

    }//GEN-LAST:event_tblLuongMouseClicked

    private void txtGioLamThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioLamThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioLamThemActionPerformed

    private void cboPhuCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPhuCapActionPerformed
        chonPhuCap();
    }//GEN-LAST:event_cboPhuCapActionPerformed

    private void cboBacLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBacLuongActionPerformed
        chonBacLuong();
    }//GEN-LAST:event_cboBacLuongActionPerformed

    private void cboLuongCoBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLuongCoBanActionPerformed
        chonLuongCoBan();
    }//GEN-LAST:event_cboLuongCoBanActionPerformed

    private void txtThucLinhCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtThucLinhCaretUpdate
        
    }//GEN-LAST:event_txtThucLinhCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboBacLuong;
    private javax.swing.JComboBox<String> cboLuongCoBan;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboPhuCap;
    private javax.swing.JComboBox<String> cboThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLuong;
    private javax.swing.JTextField txtGioLamThem;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSoNgayLam;
    private javax.swing.JTextField txtTamUng;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtThucLinh;
    private javax.swing.JTextField txtTienThuong;
    // End of variables declaration//GEN-END:variables
}
